

# This file was *autogenerated* from the file gen.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_128 = Integer(128)
from sage.all import *

# 定义函数来生成项数特定的不可约多项式
def find_min_term_irreducible_polynomial(n: int):
    R = PolynomialRing(GF(_sage_const_2 ), 'x')
    x = R.gen()

    # 尝试项数为3的多项式：形式如 x^n + x^k + 1
    for k in range(_sage_const_1 , n):
        poly = x**n + x**k + _sage_const_1 
        if poly.is_irreducible():
            return poly

    # 尝试项数为5的多项式：形式如 x^n + x^k1 + x^k2 + x^k3 + 1
    for k1 in range(_sage_const_1 , n):
        for k2 in range(_sage_const_1 , k1):
            for k3 in range(_sage_const_1 , k2):
                poly = x**n + x**k1 + x**k2 + x**k3 + _sage_const_1 
                if poly.is_irreducible():
                    return poly

    return None

n = int(input('input the level of your field (8 <= n <= 128): '))
if n < _sage_const_8  or n > _sage_const_128 :
    print('Invalid input')
    exit(_sage_const_1 )

irreducible_polynomials = {}
poly = find_min_term_irreducible_polynomial(n)
if poly:
    degrees = sorted(poly.exponents(), reverse=True)
    for degree in degrees:
        print(degree, end = ' ')



'''
print('[', end='')
for degree in degrees:
    if degree == 0:
        print(0, end='')
        break
    print(degree, end=', ')
print(']')  # 空行分隔不同的域
'''

